_commit: v0.7.9
_src_path: gh:Netbeheer-Nederland/tmpl-dp
description: Information models for the Object information model.
name: im-object
org: Netbeheer-Nederland
schema_base_uri: http://data.netbeheernederland.nl/data-product
title: Object
